spring:
      
  datasource:
    url: jdbc:mysql://localhost/testdb?useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12341234
    
  sql:    
    init:
      mode: always #h2처럼 내장 데이터베이스인 경우 embedded
      data-locations: classpath:data.sql

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create  
    defer-datasource-initialization: true 
    
    properties:
      hibernate:
#        hbm2ddl.auto: create
        format_sql: true
        use_sql_comments: true
        show-sql: true
        
        #implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        #physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#    open-in-view: false

logging:
  level:
    org:
#      springframework: DEBUG
      hibernate:
        SQL: DEBUG

jwt:
  header: Authorization
  secret: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
  token-validity-in-seconds: 180
  refreshtoken-validity-in-seconds: 1800